# -*- coding: utf-8 -*-
"""24521509.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pksvr0BaLsC-g09CehIB4U0_Ku9mXGIU
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

# Tải dữ liệu
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
data = pd.read_csv(url, sep=';')

# Chuyển về bài toán phân loại nhị phân
data['quality'] = (data['quality'] >= 6).astype(int)

X = data.drop(columns=['quality']).values
y = data['quality'].values

# Chia tập dữ liệu train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""#Asignment 1:
##Triển khai Cây quyết định (Decision Tree) bằng NumPy

 Class Node : Thiết kế cấu trúc nút lưu giữ các thông tin: Thuộc tính chia (feature), ngưỡng chia (threshold), liên kết nhánh con (left, right) và nhãn dự đoán (value) nếu nút đó được xác định là nút lá.

Gini Impurity: Sử dụng độ đo Gini để đánh giá mức độ hỗn loạn của nhãn tại một nút. Công thức cài đặt tối ưu bằng toán tử ma trận của NumPy:

Tìm kiếm điểm chia tối ưu (_best_split): Duyệt qua danh sách các thuộc tính. Nhằm tối ưu hóa hiệu năng và tránh hiện tượng nghẽn thuật toán khi đối mặt với biến liên tục, tập hợp các thresholds được thu hẹp bằng cách lấy 20 điểm phân vị (Percentiles) phân phối thay vì lấy toàn bộ giá trị duy nhất (np.unique). Điểm chia được chọn là điểm tối đa hóa lượng thông tin thu được.

Điều kiện dừng: Quá trình đệ quy dựng cây sẽ dừng lại và tạo nút lá khi rơi vào một trong các trường hợp: Đạt độ sâu tối đa (max_depth), số mẫu tại nút nhỏ hơn ngưỡng tối thiểu (min_samples_split), hoặc nút hoàn toàn tinh khiết (chỉ chứa 1 nhãn duy nhất). Nhãn của nút lá được quyết định bằng phương pháp bỏ phiếu đa số.
"""

class Node:
    def __init__(self, feature=None, threshold=None, left=None, right=None, *, value=None):
        self.feature = feature
        self.threshold = threshold
        self.left = left
        self.right = right
        self.value = value

    def is_leaf_node(self):
        return self.value is not None

class DecisionTreeNumPy:
    def __init__(self, min_samples_split=2, max_depth=10,max_features=None):
        self.min_samples_split = min_samples_split
        self.max_depth = max_depth
        self.max_features = max_features
        self.root = None

    def _gini(self, y):
      if len(y) == 0:
        return 0
      proportions = np.bincount(y) / len(y)
      return 1.0 - np.sum(proportions ** 2)
    def _split(self, X_column, split_thresh):
        left_idx = np.argwhere(X_column <= split_thresh).flatten()
        right_idx = np.argwhere(X_column > split_thresh).flatten()
        return left_idx, right_idx

    def _best_split(self, X, y):
        best_gain = -1
        split_idx, split_thresh = None, None
        current_gini = self._gini(y)
        n_features = X.shape[1]

        if self.max_features is not None:
            n_sub_features = min(n_features, self.max_features)
            feature_indices = np.random.choice(n_features, n_sub_features, replace=False)
        else:
            feature_indices = range(n_features)

        for feat_idx in feature_indices:
            X_column = X[:, feat_idx]
            if len(np.unique(X_column)) > 20:
                thresholds = np.percentile(X_column, np.linspace(5, 95, 20))
            else:
                thresholds = np.unique(X_column)

            for thr in thresholds:
                left_idx, right_idx = self._split(X_column, thr)
                if len(left_idx) == 0 or len(right_idx) == 0:
                    continue
                n = len(y)
                n_l, n_r = len(left_idx), len(right_idx)
                gini_l, gini_r = self._gini(y[left_idx]), self._gini(y[right_idx])
                child_gini = (n_l / n) * gini_l + (n_r / n) * gini_r

                gain = current_gini - child_gini
                if gain > best_gain:
                    best_gain = gain
                    split_idx = feat_idx
                    split_thresh = thr

        return split_idx, split_thresh
    def _most_common_label(self, y):

        vals, counts = np.unique(y, return_counts=True)
        return vals[np.argmax(counts)]
    def _build_tree(self, X, y, depth=0):
        n_samples, n_feats = X.shape
        n_labels = len(np.unique(y))

        # Điều kiện dừng
        if (depth >= self.max_depth or n_labels == 1 or n_samples < self.min_samples_split):
            return Node(value=self._most_common_label(y))
        # Tìm điểm chia tốt nhất
        feat_idx, thresh = self._best_split(X, y)
        if feat_idx is None:
            return Node(value=self._most_common_label(y))

        # Phát triển các nhánh con
        left_idx, right_idx = self._split(X[:, feat_idx], thresh)
        left = self._build_tree(X[left_idx, :], y[left_idx], depth + 1)
        right = self._build_tree(X[right_idx, :], y[right_idx], depth + 1)
        return Node(feature=feat_idx, threshold=thresh, left=left, right=right)
    def fit(self, X, y):
        self.root = self._build_tree(X, y)

    def _traverse_tree(self, x, node):
        if node.is_leaf_node():
            return node.value
        if x[node.feature] <= node.threshold:
            return self._traverse_tree(x, node.left)
        return self._traverse_tree(x, node.right)

    def predict(self, X):
        return np.array([self._traverse_tree(x, self.root) for x in X])

dt_numpy = DecisionTreeNumPy(max_depth=7)
dt_numpy.fit(X_train, y_train)
dt_preds = dt_numpy.predict(X_test)

print(f"Decision Tree (NumPy) F1 Score: {f1_score(y_test, dt_preds):.4f}")

"""#Assignment 2:
##Xây dụng Random Forest với Numpy
Lấy mẫu Bootstrap (_bootstrap_samples): Với mỗi cây trong tổng số n_trees cây của rừng, thuật toán tiến hành rút mẫu ngẫu nhiên có hoàn lại (replace=True) từ tập dữ liệu gốc với kích thước mẫu bằng đúng kích thước ban đầu.

(Feature Randomization): Để đảm bảo tính đa dạng và phá vỡ tính tương quan giữa các cây, tại mỗi node khi xây dựng cây con, thuật toán chỉ cho phép tìm kiếm điểm chia trên một tập con ngẫu nhiên gồm k thuộc tính thay vì duyệt qua toàn bộ không gian thuộc tính ban đầu.

(Majority Voting): Khi có dữ liệu test, dữ liệu sẽ được đưa qua tất cả các cây để lấy ra một ma trận dự đoán có kích thước (n_trees, n_samples) Thuật toán sử dụng hàm np.swapaxes(tree_preds, 0, 1) để xoay trục dữ liệu về dạng (n_samples, n_trees). Kết quả dự đoán cuối cùng của Rừng cho mỗi mẫu dữ liệu là nhãn xuất hiện với tần suất cao nhất (bầu chọn số đông) từ các cây con.
"""

class RandomForestNumPy:
    def __init__(self, n_trees=10, max_depth=10, min_samples_split=2):
        self.n_trees = n_trees
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.trees = []

    def _bootstrap_samples(self, X, y):
        n_samples = X.shape[0]
        indices = np.random.choice(n_samples, n_samples, replace=True)
        return X[indices], y[indices]

    def fit(self, X, y):
        self.trees = []
        n_features = X.shape[1]

        max_features = int(np.sqrt(n_features))

        for _ in range(self.n_trees):
            tree = DecisionTreeNumPy(
                max_depth=self.max_depth,
                min_samples_split=self.min_samples_split,
                max_features=max_features
            )
            X_sample, y_sample = self._bootstrap_samples(X, y)
            tree.fit(X_sample, y_sample)
            self.trees.append(tree)

    def predict(self, X):
        # Thu thập dự đoán từ tất cả các cây trong rừng
        tree_preds = np.array([tree.predict(X) for tree in self.trees])
        tree_preds = np.swapaxes(tree_preds, 0, 1)

        # Bầu chọn số đông
        predictions = []
        for sample_pred in tree_preds:
            vals, counts = np.unique(sample_pred, return_counts=True)
            predictions.append(vals[np.argmax(counts)])

        return np.array(predictions)

rf_numpy = RandomForestNumPy(n_trees=15, max_depth=7)
rf_numpy.fit(X_train, y_train)
rf_preds = rf_numpy.predict(X_test)

print(f"Random Forest (NumPy) F1 Score: {f1_score(y_test, rf_preds):.4f}")

"""#Assignment 3:
##Cài bằng thư viện Scikit_Learn

Nhập hai lớp mô hình trực tiếp từ thư viện: DecisionTreeClassifier và RandomForestClassifier. Cấu hình tham số kiểm soát độ sâu max_depth=7 đồng nhất cho cả mô hình thư viện và mô hình tự viết nhằm đảm bảo tính công bằng khi so sánh thực nghiệm. Đặt random_state=42 để đảm bảo kết quả có khả năng lặp lại một cách ổn định.
"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Thư viện Decision Tree
sk_dt = DecisionTreeClassifier(max_depth=7, random_state=42)
sk_dt.fit(X_train, y_train)
sk_dt_preds = sk_dt.predict(X_test)
print(f"Scikit-Learn Decision Tree F1 Score: {f1_score(y_test, sk_dt_preds):.4f}")

# Thư viện Random Forest
sk_rf = RandomForestClassifier(n_estimators=15, max_depth=7, random_state=42)
sk_rf.fit(X_train, y_train)
sk_rf_preds = sk_rf.predict(X_test)
print(f"Scikit-Learn Random Forest F1 Score: {f1_score(y_test, sk_rf_preds):.4f}")

"""#Đánh giá kết quả:
##Decision Tree và Scikit-Learn
So sánh giữa Decision Tree (NumPy) và Scikit-Learn: Mô hình tự viết bằng NumPy đạt kết quả $F_1\text{-Score}$ rất tiệm cận so với thư viện Scikit-Learn.
Sự chênh lệch nhỏ đến từ việc NumPy sử dụng kỹ thuật giới hạn 20 điểm phân vị (Percentiles) khi tìm kiếm threshold tối ưu cho biến liên tục, nhằm giảm chi phí tính toán và tăng tốc độ huấn luyện. Trong khi đó, Scikit-Learn duyệt qua toàn bộ các điểm chia khả thi trên tập dữ liệu.
## Random Forest
Ở cả hai phiên bản (NumPy và Scikit-Learn), mô hình Random Forest đều cho xu hướng cải thiện hiệu năng hoặc mang lại tính ổn định cao hơn so với Decision Tree
"""