# -*- coding: utf-8 -*-
"""24521509.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pksvr0BaLsC-g09CehIB4U0_Ku9mXGIU
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

# Tải dữ liệu (Ví dụ với rượu vang đỏ - Wine Quality Red)
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
data = pd.read_csv(url, sep=';')

# Chuyển về bài toán phân loại nhị phân
data['quality'] = (data['quality'] >= 6).astype(int)

X = data.drop(columns=['quality']).values
y = data['quality'].values

# Chia tập dữ liệu train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

class Node:
    def __init__(self, feature=None, threshold=None, left=None, right=None, *, value=None):
        self.feature = feature       # Chỉ số của tính năng dùng để chia
        self.threshold = threshold   # Ngưỡng giá trị để chia
        self.left = left             # Nhánh con bên trái
        self.right = right           # Nhánh con bên phải
        self.value = value           # Giá trị dự đoán (nếu là nút lá)

    def is_leaf_node(self):
        return self.value is not None

class DecisionTreeNumPy:
    def __init__(self, min_samples_split=2, max_depth=10,max_features=None):
        self.min_samples_split = min_samples_split
        self.max_depth = max_depth
        self.max_features = max_features
        self.root = None

    def _gini(self, y):
      if len(y) == 0:
        return 0
      proportions = np.bincount(y) / len(y)
      return 1.0 - np.sum(proportions ** 2)
    def _split(self, X_column, split_thresh):
        left_idx = np.argwhere(X_column <= split_thresh).flatten()
        right_idx = np.argwhere(X_column > split_thresh).flatten()
        return left_idx, right_idx

    def _best_split(self, X, y):
        best_gain = -1
        split_idx, split_thresh = None, None
        current_gini = self._gini(y)
        n_features = X.shape[1]

        if self.max_features is not None:
            n_sub_features = min(n_features, self.max_features)
            feature_indices = np.random.choice(n_features, n_sub_features, replace=False)
        else:
            feature_indices = range(n_features)

        for feat_idx in feature_indices:
            X_column = X[:, feat_idx]
            if len(np.unique(X_column)) > 20:
                thresholds = np.percentile(X_column, np.linspace(5, 95, 20))
            else:
                thresholds = np.unique(X_column)

            for thr in thresholds:
                left_idx, right_idx = self._split(X_column, thr)
                if len(left_idx) == 0 or len(right_idx) == 0:
                    continue
                # Tính Gini của các nhánh con
                n = len(y)
                n_l, n_r = len(left_idx), len(right_idx)
                gini_l, gini_r = self._gini(y[left_idx]), self._gini(y[right_idx])
                child_gini = (n_l / n) * gini_l + (n_r / n) * gini_r

                # Information Gain (ở đây là mức độ giảm Gini)
                gain = current_gini - child_gini
                if gain > best_gain:
                    best_gain = gain
                    split_idx = feat_idx
                    split_thresh = thr

        return split_idx, split_thresh
    def _most_common_label(self, y):

        vals, counts = np.unique(y, return_counts=True)
        return vals[np.argmax(counts)]
    def _build_tree(self, X, y, depth=0):
        n_samples, n_feats = X.shape
        n_labels = len(np.unique(y))

        # Điều kiện dừng
        if (depth >= self.max_depth or n_labels == 1 or n_samples < self.min_samples_split):
            return Node(value=self._most_common_label(y))
        # Tìm điểm chia tốt nhất
        feat_idx, thresh = self._best_split(X, y)
        if feat_idx is None:
            return Node(value=self._most_common_label(y))

        # Phát triển các nhánh con
        left_idx, right_idx = self._split(X[:, feat_idx], thresh)
        left = self._build_tree(X[left_idx, :], y[left_idx], depth + 1)
        right = self._build_tree(X[right_idx, :], y[right_idx], depth + 1)
        return Node(feature=feat_idx, threshold=thresh, left=left, right=right)
    def fit(self, X, y):
        self.root = self._build_tree(X, y)

    def _traverse_tree(self, x, node):
        if node.is_leaf_node():
            return node.value
        if x[node.feature] <= node.threshold:
            return self._traverse_tree(x, node.left)
        return self._traverse_tree(x, node.right)

    def predict(self, X):
        return np.array([self._traverse_tree(x, self.root) for x in X])

# --- Huấn luyện và Đánh giá ---
dt_numpy = DecisionTreeNumPy(max_depth=7)
dt_numpy.fit(X_train, y_train)
dt_preds = dt_numpy.predict(X_test)

print(f"Decision Tree (NumPy) F1 Score: {f1_score(y_test, dt_preds):.4f}")

class RandomForestNumPy:
    def __init__(self, n_trees=10, max_depth=10, min_samples_split=2):
        self.n_trees = n_trees
        self.max_depth = max_depth
        self.min_samples_split = min_samples_split
        self.trees = []

    def _bootstrap_samples(self, X, y):
        n_samples = X.shape[0]
        indices = np.random.choice(n_samples, n_samples, replace=True)
        return X[indices], y[indices]

    def fit(self, X, y):
        self.trees = []
        n_features = X.shape[1]

        # Công thức chuẩn của Random Forest: lấy căn bậc hai của tổng số thuộc tính tại mỗi node
        max_features = int(np.sqrt(n_features))

        for _ in range(self.n_trees):
            # Tạo cây kèm theo tham số giới hạn số thuộc tính ngẫu nhiên (max_features)
            tree = DecisionTreeNumPy(
                max_depth=self.max_depth,
                min_samples_split=self.min_samples_split,
                max_features=max_features
            )
            X_sample, y_sample = self._bootstrap_samples(X, y)
            tree.fit(X_sample, y_sample)
            self.trees.append(tree)

    def predict(self, X):
        # Thu thập dự đoán từ tất cả các cây trong rừng
        tree_preds = np.array([tree.predict(X) for tree in self.trees]) # Shape: (n_trees, n_samples)
        tree_preds = np.swapaxes(tree_preds, 0, 1)                      # Shape: (n_samples, n_trees)

        # Bầu chọn số đông (Majority voting) bằng hàm _most_common_label gián tiếp
        predictions = []
        for sample_pred in tree_preds:
            vals, counts = np.unique(sample_pred, return_counts=True)
            predictions.append(vals[np.argmax(counts)])

        return np.array(predictions)

# --- Huấn luyện và Đánh giá ---
rf_numpy = RandomForestNumPy(n_trees=15, max_depth=7)
rf_numpy.fit(X_train, y_train)
rf_preds = rf_numpy.predict(X_test)

print(f"Random Forest (NumPy) F1 Score: {f1_score(y_test, rf_preds):.4f}")

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# 1. Thư viện Decision Tree
sk_dt = DecisionTreeClassifier(max_depth=7, random_state=42)
sk_dt.fit(X_train, y_train)
sk_dt_preds = sk_dt.predict(X_test)
print(f"Scikit-Learn Decision Tree F1 Score: {f1_score(y_test, sk_dt_preds):.4f}")

# 2. Thư viện Random Forest
sk_rf = RandomForestClassifier(n_estimators=15, max_depth=7, random_state=42)
sk_rf.fit(X_train, y_train)
sk_rf_preds = sk_rf.predict(X_test)
print(f"Scikit-Learn Random Forest F1 Score: {f1_score(y_test, sk_rf_preds):.4f}")